#!/usr/bin/env sh
set -e

echo "[i] Ask for sudo password"
sudo -v

case "$(uname -s)" in
    Linux)
        if [ -f /etc/os-release ]
            then
                . /etc/os-release

                case "$ID" in
                    debian | ubuntu | pop)
                        if [[ ! -x /usr/bin/ansible ]]; then
                            echo "[i] Install Ansible"
                            sudo apt-get install -y ansible
                        fi
                        ;;

                    arch)
                        if [[ ! -x /usr/bin/ansible ]]; then
                            echo "[i] Install Ansible"
                            sudo pacman -S ansible --noconfirm
                        fi
                        ;;

                    *)
                        echo "[!] Unsupported Linux Distribution: $ID"
                        exit 1
                        ;;
                esac
            else
                echo "[!] Unsupported Linux Distribution"
                exit 1
            fi
        ;;

    *)
        echo "[!] Unsupported OS"
        exit 1
        ;;
esac
git clone https://github.com/Snipey/Playbooks.git ~/playbooks
cd ~/playbooks

#! clone the playbook repository
# Run main playbook
echo "[i] Run Playbook"
ansible-playbook --ask-become-pass -i hosts linux.yml

echo "[i] Done."